apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.8
  storage:
    storageClass: nfs-csi
    size: 2Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-ha-secret